todo/urls.py
from . import views 
from django.urls import path

app_name = 'todo'

urlpatterns =[
    path('add/', views.add, name='add'),
    path('update/<int:id>', views.update, name="update"),
    path('delete/<int:id>', views.delete, name="delete")
]

todolist/urls.py
from django.contrib import admin
from django.urls import path, include
from todo import views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('todo/', include('todo.urls')),
]

todo/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


LIST_CHOICES = (
        ('work', 'WORK'),
        ('school', 'SCHOOL'),
        ('videos', 'VIDEOS'),
      )


class List(models.Model):

      def __str__ (self):
        return self.title
      

      title = models.CharField(max_length=255)
      details = models.TextField()
      date = models.DateTimeField(default=timezone.now)
      type = models.CharField(max_length=6, choices=LIST_CHOICES, default='work')

todo/forms.py
from django import forms
from .models import List



class ListForm(forms.ModelForm):
    class Meta:
        model = List
        fields = ['title', 'details','type','date']
        

todo/views.py
from django.shortcuts import render, redirect
from .models import List
from .forms import ListForm
# Create your views here.

def index(request):
    list = List.objects.all()
    return render(request, 'index.html', {'list' : list})


def add(request):
    list=List.objects.order_by("date")
    if request.method == "POST":
        form = ListForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    form = ListForm()
    return render(request, 'add.html', {"form" :form, "list" :list})

def update(request, id):
   list = List.objects.get(id=id)
   form = ListForm(request.POST or None, instance=list) 


   if form.is_valid():
        form.save()
        return redirect('index') 
   return render(request, 'update.html', {'form': form, 'list': list})

def delete(request, id):
    list = List.objects.get(id=id)

    if request.method == 'POST':
         list.delete()
         return redirect('index') 
    return render(request, 'delete.html', {'list': list})

todo/templates/add.html
{% extends 'base.html' %}
{% block content %}


<div class="contianer d-flex d-flex-column justify-content-center mt-5">
    {% block title %} <h1>New Task</h1> {% endblock %}
</div>
<div class="contianer mb-3">
    <form class="" action="" method="post">
        {% csrf_token %}
    <div class="form-group">
        {{ form }}
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary" name="add">Add</button>
    </div>
    </form>
</div>
{% endblock %}

todo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>{% block title%} Todo List{% endblock %}</title>
</head>
<body>
    {% block body %}
    <header class="header fixed-top">
        <nav class="navbar navbar-expand-lg navbar-light bg-dark">
            <div class="container-fluid">
                <a href="{% url 'index' %}" class="navbar-brand">
                    <span style="color: white;"">To do List</span>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="true" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a style="float:right;" class="btn btn-primary" href="{% url 'todo:add' %}">New Task</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    {% endblock body %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.9.1/dist/chart.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>   
</body>
</html>

todo/templates/delete.html
<form post method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ list.title }}?</h2>
    <button type="submit" class="btn btn-warning">Confirm</button>
</form>

todo/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container mb-5">
</div>
<div class="container d-flex d-flex-column justify-content-center mb-5">
    {% block title %} <h1>My Tasks</h1> {% endblock %}
</div>
<div>
    {% for list in list %}
    <div class="row">
        <div class="container card mb-3">
            <p>{{ list.id }} <span style="color:blue;">{{ list.title }}</span></p>
            <p>{{ list.details }}</p>
            <p><span style="color:blue;">Due Date:</span> {{ list.date }}</p>
            <p><span style="color:red;">Type of Task:</span> {{ list.type }}</p>
            <div class="contianer">
                <a  href="{% url 'todo:update' list.id%}" class="btn btn-success">Update Task</a>
                <a  href="{% url 'todo:delete' list.id%}" class="btn btn-danger">Delete Task</a>
            </div>
        </div>
        {% empty %}
        <h4>Hit the Button to create a list</h4>
        {% endfor %}
    </div>
</div>
<div class="contianer">
    <a  href="{% url 'todo:add' %}" class="btn btn-primary">New Task</a>
   
</div>
{% endblock %}

todo/templates/update.html
{% extends 'base.html' %}
{% block content %}


<div class="contianer d-flex d-flex-column justify-content-center mt-5">
    {% block title %} <h1>Update Task</h1> {% endblock %}
</div>
<div class="contianer mb-3">
    <form class="" action="" method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit" value="Update" class="btn btn-primary" name="Update">Update</button>
    </form>
</div>
{% endblock %}